spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
externalUrl: https://redsky.target.com/v2/pdp/tcin/13860428?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics
      